language: node_js
node_js:
- '6'
branches:
  only:
  - master
  - develop
  - /^v.*$/
before_script:
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install --quiet -g gulp
- npm install
before_deploy:
- npm run compile
deploy:
    skip_cleanup: true
    - provider: npm
      email: pkerpedjiev@gmail.com
      api_key:
          secure: lX+QiVA0uWWAD5FajOC2nJGRI4CjSh/MoPY9KTSsJBVATmyms5nNHB8FfYT2PBAikRR65ap5QbTnia5TajgstTduWj5AG7MnBblexB6Y/T7kPX7fKf0iknWex55ZU+FP6RnwZCyyxhORd7FstO3gf8IjulTYNyztK2jAQ4yAapWOdLbvgpo/OHdDVVxFWNqH0PbdFyAQs9KEZaR2IwtpV4KgVUSMKY6vUC+lPvUE8gp//GqKjizdLT/GXnaabXZqcljp3zrhENmOI+525dbYXz0ApCJw7MVS+2quo2j0NqrvVAUey8zmh9+nt5dAX8Vsv2wCZmAe8hUNsWujX48E2v9T5ibeP1SrzhDybGtzCxSY1WjnK23SXPL9w9kfVxUqQAn76OqpQeTGIjgM3ubyNxS/QE4iocQ6YPUrdJLFQL0eG2P9lrvBaBftoM8RtoY6GKDIFxrnE2HKKBwqngEdj7ujuagRbk6MCFlaCvjSQQ6ev1LNc/GFwAHiOW68HDjKJQGxi0VpVUuwgvOaYaE/hUXaMeHOPdYUnDxpDHBDP3QHz2cXhWwsF7HTV8ej/P9LCbjSd8Rs9cfzfQZtFBSzygMUX/ilIVF+WUpdHxV25aUPZsjm4GqEgkTV5gdDlxeTrrB4GMNwCkJQBiigAY8nhbu5UxalhhbH6zwhkEcqBTg=
      on:
        tags: true
        branch: master
    - provider: releases
      file: dist.zip
      api_key:
          secure: Pr3uxqR7ihrbpIOecTNaI4lJ1eqwNqpzqtWptVOffyZfmJ3EEfJu2swRgpr7Zi2AP6R5IhVdZJ9ZkRFqV0ei8S+OzFSNhYMoqr1ISvP7VxVKxUaDhWeqEE1umRJ6rENQko8mxqC9e8zW8Mx7U/IAnHXfHFlicYwrt5y/xGBOjhaF9W9sPBPG41QTaLswP1Cp5Tyti2rlZ1K6cWFX01gQugVJsdK5/b27wjoq/LKez6xRu2fa0i+FRGhKiYDh/OCduSh4AIEw9jFssjxC87eHP4CyIBYlUhRSqgcT3DMsuw7uxiVBUwrqB2B9GgcWspmN5LWNpHNE1Y/1e2xgPruxu/bhyXd3ZDNdD4iLt/eGVLbLVOjzK8xuhL7X0H9zd4DtheSfOBj6PRw7qUbLiSHt/qUVo9SosWhzOz/2Q0l2+7d8n/oJx5dzNKzQeVrxp5pM9aMph467BxBJQ6h8/KjXf3FO84DmHUyRR4yW4x+LlKlYWpmtQoOf8tjt1Jd0wj7fZyvq0UVcTSBFdQiAsaU75ItBOFXZaUgqYJqKKtT8+DKzbGd8Jw78qzmWuiPkvMh+FxAzVBQq9D1Jr8jFlUz3iBc+BC8N+DV+1tFKlgaBq/SxJ6jcXwhqOBHva6F2RctbG77M94hYYxcmtazO2QwADj2elvxsje7B2XR8O+WPuNs=
      on:
        tags: true
        branch: master
