dist: trusty
language: node_js
node_js:
- '9'
addons:
  apt:
    packages:
      - xvfb
before_install:
    # Make sure we have a version which supports "npm ci".
    # https://github.com/travis-ci/travis-ci/issues/4653#issuecomment-379397837
    - dpkg --compare-versions `npm -v` ge 6.5.0 || npm i -g npm@^6.5.0
install:
    - npm install -g xvfb-maybe
before_script:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install --quiet -g gulp
    - npm install -g jsdoc
    - npm clean-install
script:
    - ./travis_build_test.sh
before_deploy:
    - wget http://repo.continuum.io/miniconda/Miniconda3-4.3.21-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -f -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - conda install --yes python=3.6
    - pip install --user -r docs/requirements.txt
    - cd docs; ./build.sh; cd -
deploy:
  - &s3
    provider: s3
    skip_cleanup: true
    access_key_id: AKIAZLS5EJLSAIAWUCX3
    secret_access_key:
      secure: cUzdgd+U/V2gi7OeUbUrd6QSC8u/ixrOYj3xvVao4G40PuxYMLpUqZ6kUF/7sAwGbugq9t8tHhhEaL1ByVDmH+F9LJG68tFbjsqQKaTo1OYYK49i9SeXLkgwnUacn8wYAT0DwMg/ghsiTjBXIRE+aL1JZX5j1lx0MhKNuit+1zP7TB4F+nltDGasZY2sPP+4CNJLmpF7Yrt2YIa+DGA3sFhsVqTLyVTtJwNAPS5gp7NgWj1dcfYxs/0PJ/SZRVblUXtjnAY353EdOjeeTSNDPnQhK5UUUVG83hP7iIC4r1zbaKxlgKE0aDbs8RLovrbS71r079m99aHMiALSs/cFNojcXRBerM/kgkqcQElMkkN2dJY9nGgu1WHJC3X36cXZ4d33OJxhAaP3fz9B7Vcw6X9BC1g/F+IsdozsNOmSqZSEva1Z2l09lIe5ZNxPEP/Yhu/2tWb+zFfPr5hwmsx9fsdXIqxtctYwA9ec83nj1pJdgYNfs9Ul0HJcQdB+T2G7qT3wA1HZEMjoKvsVw7pV8WHXeXJx+8VI01L6YMsOY2DIeB/maYgVcc4FoxU9dVKXpXN2FoHDNS98C4V5tuV+baIonaW451W2TTu5lPxtT7lKyRfRVh+C/w01byc64fG6AhanAwlO0m9KShoS6RQkpIUqx8OnQ+3F9YH+xYGEa6Q=
    bucket: docs.higlass.io
    local-dir: docs/_build/html
    acl: public_read
    on:
      branch: master
  - <<: *s3
    bucket: docs-develop.higlass.io
    on:
      branch: develop
  - <<: *s3
    bucket: docs-latest.higlass.io
    on:
      all_branches: true

  - provider: npm
    skip_cleanup: true
    file: dist.zip
    email: pkerpedjiev@gmail.com
    api_key:
        secure: AGI4b3s8m+mKdVAVBR+d5EdYdYAeLhFy76o8WzQ7KwGSIAsIfmwjejqs4BRvq2m3kDdUqNF4fUhG1L2yXsqGXdKqDYnICL+IiKJAKrtdrsx4Y8J31OdeYX8J4MrYzFYsHAyg2bO0D2JNKe0K5b1ykks3qZd9p+Q/4jMjekmNB/T4rBOKjg1bxm0deULQabsLyonjY/IoLc+vjuNmT9VLw9SXw5d8yWTeWszHL8QmQ/UFKZVxF1EfaxJU/9/R/QKQgrAXHsElGfS9+dfhMmZTW8+3kNbB8/lHGkoF+9LrqnRWI6/R8OorqHSLmomfJJuK4iS2Z7Ull561vG67lNrgj7EZ3F2Rjrn4I82T2V/fYBCU/xvIsp2a+MUXvScWu3ONtNJCLGXL7qHQuVN6UjTyVH9J010fIz1qeY264Q/HSVv+PnAueN6e3j9RmrYIf4bVL9OxsNPhOZbUOi/xvg/WBkNifhrT/n65wgopyT5tzwK9Tk8Kyp6aJlaDsqFBtc7gZhOn8MIPsAYAvszfXlNHFqfOrvRQqV/UWoaBkBFEVJwlVZzUWmbNz0wIFs3QJjabR5/wR8GRUpRmugTMR1OE6JYwiIGhteW55p9Wm1SbHZw7RT3VIENpovxmGhbT4TxsZ8UcFk6fknIUH8F1S7K2+Uwxu5Wb0DT7SoD/Lfh0u+E=
    on:
      branch: master
      tags: true
  - provider: releases
    skip_cleanup: true
    file: dist.zip
    api_key:
        secure: Pr3uxqR7ihrbpIOecTNaI4lJ1eqwNqpzqtWptVOffyZfmJ3EEfJu2swRgpr7Zi2AP6R5IhVdZJ9ZkRFqV0ei8S+OzFSNhYMoqr1ISvP7VxVKxUaDhWeqEE1umRJ6rENQko8mxqC9e8zW8Mx7U/IAnHXfHFlicYwrt5y/xGBOjhaF9W9sPBPG41QTaLswP1Cp5Tyti2rlZ1K6cWFX01gQugVJsdK5/b27wjoq/LKez6xRu2fa0i+FRGhKiYDh/OCduSh4AIEw9jFssjxC87eHP4CyIBYlUhRSqgcT3DMsuw7uxiVBUwrqB2B9GgcWspmN5LWNpHNE1Y/1e2xgPruxu/bhyXd3ZDNdD4iLt/eGVLbLVOjzK8xuhL7X0H9zd4DtheSfOBj6PRw7qUbLiSHt/qUVo9SosWhzOz/2Q0l2+7d8n/oJx5dzNKzQeVrxp5pM9aMph467BxBJQ6h8/KjXf3FO84DmHUyRR4yW4x+LlKlYWpmtQoOf8tjt1Jd0wj7fZyvq0UVcTSBFdQiAsaU75ItBOFXZaUgqYJqKKtT8+DKzbGd8Jw78qzmWuiPkvMh+FxAzVBQq9D1Jr8jFlUz3iBc+BC8N+DV+1tFKlgaBq/SxJ6jcXwhqOBHva6F2RctbG77M94hYYxcmtazO2QwADj2elvxsje7B2XR8O+WPuNs=
    on:
      tags: true
      branch: master
